import express from "express";
import categoryRouter from "./category";
// import addressRouter from "./address";
import authRouter from "./auth";
import brandRouter from "./brand";
import cartItemRouter from "./cart-item";
import cartRouter from "./cart";
import orderItemRouter from "./order-item";
import orderRouter from "./order";
import paymentRouter from "./payment";
import productOptionGroupRouter from "./product-option-group";
import productOptionRouter from "./product-option";
import productVariantRouter from "./product-variant";
import productRouter from "./product";
import reviewRouter from "./review";
import saleRouter from "./sale";
import storeRouter from "./store";
import userRouter from "./user";
import wishlistRouter from "./wishlist";
import promotionRouter from "./promotion";

const router = express.Router();

// router.use('/address', addressRouter);
router.use('/auth', authRouter);
router.use('/brands', brandRouter);
router.use('/cart-items', cartItemRouter);
router.use('/carts', cartRouter);
router.use('/categories', categoryRouter);
router.use('/order-items', orderItemRouter);
router.use('/orders', orderRouter);
router.use('/payments', paymentRouter);
router.use('/product-option-groups', productOptionGroupRouter);
router.use('/product-options', productOptionRouter);
router.use('/product-variants', productVariantRouter);
router.use('/products', productRouter);
router.use('/promotions', promotionRouter);
router.use('/reviews', reviewRouter);
router.use('/sales', saleRouter);
router.use('/stores', storeRouter);
router.use('/users', userRouter);
router.use('/wishlists', wishlistRouter);

export default router;