import express from "express";
import categoryRouter from "./category";
// import addressRouter from "./address";
import authRouter from "./auth";
import brandRouter from "./brand";
import cartItemRouter from "./cart-item";
import cartRouter from "./cart";
import orderItemRouter from "./order-item";
import orderRouter from "./order";
import paymentRouter from "./payment";
import productOptionGroupRouter from "./product-option-group";
import productOptionRouter from "./product-option";
import productVariantRouter from "./product-variant";
import productRouter from "./product";
import reviewRouter from "./review";
import saleRouter from "./sale";
import storeRouter from "./store";
import userRouter from "./user";
import wishlistRouter from "./wishlist";
import promotionRouter from "./promotion";
import { authMiddleware } from "../middleware/auth";

const router = express.Router();

// router.use('/address', addressRouter);
router.use('/auth', authRouter);
router.use('/brands', authMiddleware, brandRouter);
router.use('/cart-items', authMiddleware, cartItemRouter);
router.use('/carts', authMiddleware, cartRouter);
router.use('/categories', authMiddleware, categoryRouter);
router.use('/order-items', authMiddleware, orderItemRouter);
router.use('/orders', authMiddleware, orderRouter);
router.use('/payments', authMiddleware, paymentRouter);
router.use('/product-option-groups', authMiddleware, productOptionGroupRouter);
router.use('/product-options', authMiddleware, productOptionRouter);
router.use('/product-variants', authMiddleware, productVariantRouter);
router.use('/products', authMiddleware, productRouter);
router.use('/promotions', authMiddleware, promotionRouter);
router.use('/reviews', authMiddleware, reviewRouter);
router.use('/sales', authMiddleware, saleRouter);
router.use('/stores', authMiddleware, storeRouter);
router.use('/users', authMiddleware, userRouter);
router.use('/wishlists', authMiddleware, wishlistRouter);

export default router;